# ... your existing content above ...

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # ⬇️ Add this step
      - name: Copy report & figure into site
        run: |
          # Make report the site index
          cp -f reports/report.html _site/index.html
          # Optionally publish the ATT figure alongside it
          mkdir -p _site/assets
          [ -f figures/att_summary.png ] && cp figures/att_summary.png _site/assets/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    # ... unchanged ...
