name: Render report (HTML via nbconvert)
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Convert analysis.ipynb -> HTML
        run: |
          mkdir -p results docs
          if [ -f analysis.ipynb ]; then
            jupyter nbconvert --to html analysis.ipynb --output results/report.html
            cp results/report.html docs/
          else
            echo "<!doctype html><title>No notebook</title><h1>No analysis.ipynb found</h1>" > docs/index.html
          fi
      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: |
            results/**
            docs/**
