# ... (lines above) ...
      - name: Install nbconvert & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert

<<<<<<< HEAD
=======
      # <<< ADD THIS NEW STEP >>>
>>>>>>> 3f63e6c0e8f5fa5412897250722819d8695c2607
      - name: Create dummy data for CI
        run: |
          mkdir -p data
          echo "week,region,incidence,treated" > data/ontario_cases.csv
          echo "2021-01-01,A,10,1" >> data/ontario_cases.csv
          echo "2021-12-01,A,8,1" >> data/ontario_cases.csv
          echo "2021-01-01,B,11,0" >> data/ontario_cases.csv
          echo "2021-12-01,B,9,0" >> data/ontario_cases.csv
<<<<<<< HEAD
          
=======

>>>>>>> 3f63e6c0e8f5fa5412897250722819d8695c2607
      - name: Run Python pipeline to generate figures
        run: |
          python run_analysis.py
# ... (lines below) ...
