name: Validate results
on:
  push: { branches: [ "main" ] }
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analysis
        run: |
          python run_analysis.py

      - name: Show tree
        run: |
          echo "::group::tree -L 3"
          sudo apt-get update && sudo apt-get install -y tree >/dev/null 2>&1 || true
          tree -L 3 || true
          echo "::endgroup::"

      - name: Sanity-check results/results.json
        run: |
          python - << 'PY'
import os, json, math, sys
p = "results/results.json"
assert os.path.exists(p), f"Missing {p}"
with open(p) as f:
    res = json.load(f)
print("results.json:", res)
# light sanity on numeric fields if present
for k in ("did_att","did_se","did_p","psm_att"):
    if k in res:
        v = res[k]
        assert isinstance(v, (int,float)) and math.isfinite(v), f"{k} not finite: {v}"
PY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis-artifacts
          path: |
            results/**
            figures/**
