name: Validate results
on:
  push: { branches: [ "main" ] }
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        run: |
          python run_analysis.py  # or: python scripts/run_analysis.py
      - name: Sanity checks
        run: |
          python - << 'PY'
import os, pandas as pd
candidates = ["results/metrics.csv","results/did_output.csv"]
target = next((p for p in candidates if os.path.exists(p)), None)
assert target, "Expected results CSV not found."
df = pd.read_csv(target)
print(df.head())
assert len(df)>0, "Results file is empty."
PY
      - name: Upload figures
        uses: actions/upload-artifact@v4
        with:
          name: figures
          path: |
            figures/**
            results/**/*.png
            results/**/*.pdf
            results/**/*.csv
