# ... (lines above) ...
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # <<< ADD THIS NEW STEP >>>
      - name: Create dummy data for CI
        run: |
          mkdir -p data
          echo "week,region,incidence,treated" > data/ontario_cases.csv
          # Add a few rows satisfying date and column requirements (pre/post intervention)
          echo "2021-01-01,A,10,1" >> data/ontario_cases.csv
          echo "2021-12-01,A,8,1" >> data/ontario_cases.csv
          echo "2021-01-01,B,11,0" >> data/ontario_cases.csv
          echo "2021-12-01,B,9,0" >> data/ontario_cases.csv

      - name: Run pipeline
        run: |
          python run_analysis.py
# ... (lines below) ...
