on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show HEAD + file list (pre)
        run: |
          git log -1 --oneline
          echo "::group::tree -L 2 (pre)"
          sudo apt-get update >/dev/null 2>&1 || true
          sudo apt-get install -y tree >/dev/null 2>&1 || true
          tree -L 2 || true
          echo "::endgroup::"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert jupyter pycausalimpact seaborn matplotlib statsmodels scikit-learn pandas numpy

      - name: Run analysis (and print summary)
        run: |
          set -e
          mkdir -p results figures
          python run_analysis.py
          echo "::group::results.json"
          python - << 'PY'
import json
import os

p = "results/results.json"
assert os.path.exists(p), f"Missing {p}"
with open(p) as f:
    data = json.load(f)
print(json.dumps(data, indent=2))
PY
          echo "::endgroup::"

      - name: Sanity checks (numeric & finite)
        run: |
          python - << 'PY'
import json
import math
with open("results/results.json") as f:
    res = json.load(f)
for k in ("did_att", "did_se", "did_p", "psm_att"):
    if k in res:
        v = res[k]
        assert isinstance(v, (int, float)) and math.isfinite(v), f"{k} not finite: {v}"
print("Sanity OK")
PY

      - name: Show tree (post)
        run: |
          echo "::group::tree -L 3 (post)"
          tree -L 3 || true
          echo "::endgroup::"
      - name: Upload artifacts (if present)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: analysis-artifacts
          path: |
            results/**
            figures/**
          if-no-files-found: ignore
