name: validate-results
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run analysis
        run: |
          python -m src.run_analysis
      - name: Validate results.json
        run: |
          python - << 'PY'
          import json, math, pathlib
          p = pathlib.Path("results/results.json")
          res = json.loads(p.read_text(encoding="utf-8"))
          for k in ["did","psm","bsts","artifacts","metadata"]:
              assert k in res, f"Missing key: {k}"
          def ok(x): return x is None or (isinstance(x,(int,float)) and math.isfinite(x))
          assert ok(res["did"].get("att"))
          assert ok(res["psm"].get("att"))
          assert ok(res["bsts"].get("att"))
          print("✅ results.json looks good")
          PY
      - uses: actions/upload-artifact@v4
        with:
          name: analysis-artifacts
          path: |
            results/**
            figures/**
