name: Validate results
on:
  push: { branches: [ "main" ] }
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run analysis
        run: |
          python run_analysis.py
      - name: Sanity-check results/results.json
        run: |
          python - << 'PY'
import os, json, math
p = "results/results.json"
assert os.path.exists(p), f"Missing {p}"
res = json.load(open(p))
print("results.json:", res)
for k in ("did_att","did_se","did_p","psm_att","psm_se","pretrend_p"):
    if k in res and res[k] is not None:
        v = res[k]; assert isinstance(v, (int,float)) and math.isfinite(v), f"{k} not finite: {v}"
PY
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: analysis-artifacts
          path: |
            results/**
            figures/**
