name: Validate results

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create dummy data for CI
        run: |
          mkdir -p data
          echo "week,region,incidence,treated" > data/ontario_cases.csv
          echo "2021-01-01,A,10,1" >> data/ontario_cases.csv
          echo "2021-12-01,A,8,1" >> data/ontario_cases.csv
          echo "2021-01-01,B,11,0" >> data/ontario_cases.csv
          echo "2021-12-01,B,9,0" >> data/ontario_cases.csv

      - name: Run pipeline
        run: |
          python run_analysis.py

      - name: Sanity checks
        run: |
          python - << 'PY'
import pandas as pd, os, sys
p = "results/metrics.csv"
alt = "results/did_output.csv" 
target = p if os.path.exists(p) else alt

assert os.path.exists(target), "Expected results CSV not found."
df = pd.read_csv(target)
print("Result head:\n", df.head())
assert len(df) > 0, "Results file is empty."
PY

      - name: Upload figures & results
        uses: actions/upload-artifact@v4
        with:
          name: figures-and-results
          path: |
            figures/**
            results/**/*.png
            results/**/*.pdf
            results/**/*.csv
